### ISSUE TITLE
Why is this better than WebRenderer for Dioxus

### ISSUE THREAD

**Issue by sirati** [jkelleyrtp/stylo-dioxus#5]
Hello,
I am trying to understand the state of [dioxus](https://github.com/dioxuslabs/dioxus). I am sure I must have missed it, but I got the following question: Why does dioxus prefer to write its own native renderer ([blitz](https://github.com/dioxuslabs/blitz) and [this](https://github.com/jkelleyrtp/stylo-dioxus)) instead of adopting [webrender](https://github.com/servo//webrender).
I understand that webrender does not use WGPU but OpenGL2.1, so here one would need to port that WebGL to support ios
i also understand that servo currently does all the glue that makes the layouter and css integrate, but with a custom renderer that also would have to be implemented anyway

so would be great if you could explain abit on this, so that it is documented

**Comment by sepcnt** [comment]
`webrender` is more similar to [`vello`](https://github.com/linebender/vello)

**Comment by jkelleyrtp** [comment]
We wanted to use WGPU as a platform to be open to any other libraries that also use WGPU, which seems to be where the Rust ecosystem is moving these days. WebRender doesn't have quite many examples right now and only solves a small portion of the whole problem (layout, styling, text, input css). There's a chance we do move to webrenderer one day, but our current prototypes with Vello and Taffy seem promising.
